---
- hosts: all
  become: true
  vars:
    ansible_sudo_pass: "{{ ansible_ssh_pass }}"
       
  tasks:
  - name: copy war
    copy:
      src: /var/lib/jenkins/workspace/Soufiane-Deploy-On-Container-Ansible/webapp/target/webapp.war
      dest: /opt/docker/Soufiane
      
  - name: Stop current container
    command: docker stop bootcamp-container-ansible
    ignore_errors: yes
    
  - name: remove stopped container
    command: docker rm bootcamp-container-ansible
    ignore_errors: yes
    
  # - name: remover docker images # Clean up task
  #   command: docker rmi simple-devops-container:latest
  #   ignore_errors: yes # May not find image if first run
    
  - name: create docker image using war file
    command: docker build -t bootcamp-container-ansible .
    args:
      chdir: /opt/docker/Soufiane
      
  - name: run container
    command: docker run -d --name bootcamp-container-ansible -p 8082:8080 bootcamp-container-ansible
