---
- hosts: all
  become: true #need to add this
       
  tasks:
  - name: copy war
    copy:
      src: /var/lib/jenkins/workspace/Soufiane-Deploy-On-Container-Ansible/webapp/target/webapp.war
      dest: /opt/docker/Soufiane
      
  - name: Stop current container
    command: docker stop simple-devops-container
    ignore_errors: yes
    
  - name: remove stopped container
    command: docker rm simple-devops-container
    ignore_errors: yes
    
  - name: remover docker images # Clean up task
    command: docker rmi simple-devops-container:latest
    ignore_errors: yes # May not find image if first run
    
  - name: create docker image using war file
    command: docker build -t simple-devops-container:latest .
    args:
      chdir: /opt/docker/Soufiane
      
  - name: run container
    command: docker run -d --name simple-devops-container -p 8081:8080 simple-devops-container:latest
